name: 'Nx set SHAs'
description: 'Derives appropriate SHAs for base and head for use in `nx affected` commands, optionally setting them as environment variables for the current job'

inputs:
  main-branch-name:
    description: 'The name of the main branch in your repo, used as the target of PRs. E.g. main, master etc'
    default: 'main'

outputs:
  base:
    description: The value intended for use with --base or NX_BASE in all subsequent `nx affected` commands within the current workflow
    value: ${{ steps.setSHAs.outputs.base }}
  head:
    description: The value intended for use with --head or NX_HEAD in all subsequent `nx affected` commands within the current workflow
    value: ${{ steps.setSHAs.outputs.head }}

runs:
  using: 'composite'
  steps:
    - name: Set base and head SHAs used for nx affected
      id: setSHAs
      shell: bash
      run: node ${{ github.action_path }}/dist/index.js
      with:
        mainBranchName: ${{ inputs.main-branch-name }}
        evenName: ${{ github.event_name }}

    - name: Log base and head SHAs used for nx affected
      shell: bash
      run: |
        echo "Base SHA"
        echo ${{ steps.setSHAs.outputs.base }}
        echo ""
        echo "Head SHA"
        echo ${{ steps.setSHAs.outputs.head }}
        echo ""
    - name: Optionally set the derived SHAs as NX_BASE and NX_HEAD environment variables for the current job
      shell: bash
      run: |
        # Built-in Github action conditionals are not supported in composite steps so have to check manually in bash
        if [ "${{ inputs.set-environment-variables-for-job }}" = "true" ]; then
          echo "NX_BASE=${{ steps.setSHAs.outputs.base }}" >> $GITHUB_ENV
          echo "NX_HEAD=${{ steps.setSHAs.outputs.head }}" >> $GITHUB_ENV
          echo "NX_BASE and NX_HEAD environment variables have been set for the current Job"
        fi